/* eslint-disable no-console */
require('../config/env');

const connectDB = require('../config/db');
const Admin = require('../models/Admin');
const Cart = require('../models/Cart');
const Category = require('../models/Category');
const Product = require('../models/Product');

const IMAGES = {
  kitPurple: '/assets/paw/Cat Food Kit.png',
  kitRed: '/assets/paw/Cat Food Kit1.png',
  osmonSmall: '/assets/paw/image 654.png',
  osmonPodium: '/assets/paw/image 653.png',
  bowlFood: '/assets/paw/cfc3d7f844b024807049920fc1a7bb55 1.png',
};

const CATEGORIES = [
  {
    name: 'Hạt khô cho mèo',
    slug: 'hat-kho-cho-meo',
    sortOrder: 1,
    description: 'Thức ăn hạt cho bữa chính hằng ngày.',
  },
  {
    name: 'Pate & sốt mèo',
    slug: 'pate-sot-meo',
    sortOrder: 2,
    description: 'Đồ ăn ướt giúp bổ sung nước và đổi vị.',
  },
  {
    name: 'Meal kit cá nhân hóa',
    slug: 'meal-kit-ca-nhan-hoa',
    sortOrder: 3,
    description: 'Combo phối khẩu phần theo độ tuổi và nhu cầu sức khỏe.',
  },
  {
    name: 'Snack & treat',
    slug: 'snack-treat',
    sortOrder: 4,
    description: 'Bánh thưởng và topping cho mèo.',
  },
  {
    name: 'Sữa & nước uống',
    slug: 'sua-nuoc-uong',
    sortOrder: 5,
    description: 'Sữa, nước bù khoáng và sản phẩm bổ sung.',
  },
  {
    name: 'Phụ kiện ăn uống',
    slug: 'phu-kien-an-uong',
    sortOrder: 6,
    description: 'Bát ăn, máy ăn và máy nước cho mèo.',
  },
];

const PRODUCT_DEMOS = [
  {
    sku: 'PW-DEMO-001',
    name: 'Kit Toàn Diện Cá Ngừ & Gà',
    brand: 'PawWorld',
    categorySlug: 'meal-kit-ca-nhan-hoa',
    price: 450000,
    salePrice: null,
    stock: 42,
    weight: '1.5kg + 7 gói pate',
    flavor: 'Cá ngừ & gà',
    ageRange: 'adult',
    foodType: 'mixed',
    healthNeeds: ['digestion', 'hairball'],
    shortDescription: 'Gói tuần 1.5kg cho mèo trưởng thành, phối hạt và pate.',
    description: 'Meal kit phối hạt khô, pate ướt và topping chất xơ để mèo ăn ngon hơn mỗi ngày.',
    image: IMAGES.kitPurple,
    tags: ['meal kit', 'tieu hoa', 'long muot'],
    isFeatured: true,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 128,
    soldCount: 580,
    viewCount: 3200,
  },
  {
    sku: 'PW-DEMO-002',
    name: 'Kit Mèo Con Osmon Gà Non',
    brand: 'Osmon',
    categorySlug: 'meal-kit-ca-nhan-hoa',
    price: 220000,
    salePrice: null,
    stock: 36,
    weight: '3 ngày',
    flavor: 'Gà non',
    ageRange: 'kitten',
    foodType: 'mixed',
    healthNeeds: ['digestion'],
    shortDescription: 'Mix ướt/khô 3 ngày dành riêng cho hệ tiêu hóa non nớt.',
    description: 'Khẩu phần mềm, thơm và dễ tiêu hóa cho mèo dưới 1 năm tuổi.',
    image: IMAGES.osmonPodium,
    tags: ['kitten', 'osmon', 'tieu hoa'],
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 94,
    soldCount: 420,
    viewCount: 2210,
  },
  {
    sku: 'PW-DEMO-003',
    name: 'Hạt Khô Piko Adult 5-in-1',
    brand: 'Piko',
    categorySlug: 'hat-kho-cho-meo',
    price: 450000,
    salePrice: 399000,
    stock: 64,
    weight: '1.5kg',
    flavor: 'Cá hồi',
    ageRange: 'adult',
    foodType: 'dry',
    healthNeeds: ['hairball'],
    shortDescription: 'Hạt khô hỗ trợ giảm búi lông và duy trì cân nặng.',
    description: 'Công thức nhiều chất xơ, bổ sung omega và taurine cho mèo trưởng thành.',
    image: IMAGES.osmonSmall,
    tags: ['hat kho', 'hairball'],
    isFeatured: true,
    rating: 4.7,
    reviewCount: 76,
    soldCount: 312,
    viewCount: 1740,
  },
  {
    sku: 'PW-DEMO-004',
    name: 'Pate Purr Feast Cá Hồi',
    brand: 'Purr Feast',
    categorySlug: 'pate-sot-meo',
    price: 450000,
    salePrice: null,
    stock: 58,
    weight: '12 gói x 80g',
    flavor: 'Cá hồi',
    ageRange: 'adult',
    foodType: 'wet',
    healthNeeds: ['skin', 'hairball'],
    shortDescription: 'Pate ướt giàu omega, phù hợp mèo kén ăn và cần đẹp lông.',
    description: 'Đồ ăn ướt mềm, thơm, bổ sung omega-3 và vitamin E cho da khỏe lông mượt.',
    image: IMAGES.kitRed,
    tags: ['pate', 'da long'],
    rating: 4.8,
    reviewCount: 112,
    soldCount: 460,
    viewCount: 2360,
  },
  {
    sku: 'PW-DEMO-005',
    name: 'Kit Tối Ưu Sức Khỏe KittyCat',
    brand: 'KittyCat',
    categorySlug: 'meal-kit-ca-nhan-hoa',
    price: 450000,
    salePrice: 420000,
    stock: 24,
    weight: '3 ngày + súp thưởng',
    flavor: 'Gà & bí đỏ',
    ageRange: 'senior',
    foodType: 'mixed',
    healthNeeds: ['digestion', 'skin'],
    shortDescription: 'Gói 3 ngày cho mèo lớn tuổi, ưu tiên tiêu hóa và da khỏe.',
    description: 'Khẩu phần mềm, ít béo, có chất xơ hòa tan và vitamin nhóm B.',
    image: IMAGES.bowlFood,
    tags: ['senior', 'tieu hoa', 'da khoe'],
    rating: 4.6,
    reviewCount: 38,
    soldCount: 170,
    viewCount: 980,
  },
  {
    sku: 'PW-DEMO-006',
    name: 'Hạt Khô Pikku Serene Bites',
    brand: 'Pikku',
    categorySlug: 'hat-kho-cho-meo',
    price: 450000,
    salePrice: null,
    stock: 31,
    weight: '1.2kg',
    flavor: 'Cá ngừ & cúc la mã',
    ageRange: 'adult',
    foodType: 'dry',
    healthNeeds: ['skin'],
    shortDescription: 'Hạt khô cho mèo nhạy cảm, hỗ trợ da và giảm kích ứng.',
    description: 'Công thức protein vừa phải, thêm dầu cá và chiết xuất cúc la mã.',
    image: IMAGES.osmonSmall,
    tags: ['hat kho', 'nam da'],
    rating: 4.5,
    reviewCount: 59,
    soldCount: 246,
    viewCount: 1290,
  },
  {
    sku: 'PW-DEMO-007',
    name: 'Pate Kitten Gà Sữa Non',
    brand: 'Nature Bridge',
    categorySlug: 'pate-sot-meo',
    price: 32000,
    salePrice: null,
    stock: 180,
    weight: '80g',
    flavor: 'Gà sữa',
    ageRange: 'kitten',
    foodType: 'wet',
    healthNeeds: ['digestion', 'mother'],
    shortDescription: 'Pate mềm cho mèo con và mèo mẹ đang cho bú.',
    description: 'Đạm dễ hấp thu, bổ sung canxi và taurine để hỗ trợ giai đoạn tăng trưởng.',
    image: IMAGES.kitRed,
    tags: ['pate', 'kitten', 'meo me'],
    isFeatured: true,
    rating: 4.9,
    reviewCount: 211,
    soldCount: 930,
    viewCount: 4100,
  },
  {
    sku: 'PW-DEMO-008',
    name: 'Hạt Mèo Con SmartHeart DHA',
    brand: 'SmartHeart',
    categorySlug: 'hat-kho-cho-meo',
    price: 125000,
    salePrice: 99000,
    stock: 92,
    weight: '400g',
    flavor: 'Gà & cá',
    ageRange: 'kitten',
    foodType: 'dry',
    healthNeeds: ['digestion'],
    shortDescription: 'Hạt nhỏ, dễ nhai cho mèo con dưới 1 năm tuổi.',
    description: 'Bổ sung DHA, taurine và prebiotic để hỗ trợ tiêu hóa và phát triển thị lực.',
    image: IMAGES.osmonPodium,
    tags: ['hat kho', 'kitten'],
    isBestSeller: true,
    rating: 4.7,
    reviewCount: 88,
    soldCount: 520,
    viewCount: 2500,
  },
  {
    sku: 'PW-DEMO-009',
    name: 'Pate Senior Cá Trắng',
    brand: 'Unicharm',
    categorySlug: 'pate-sot-meo',
    price: 36000,
    salePrice: null,
    stock: 120,
    weight: '70g',
    flavor: 'Cá trắng',
    ageRange: 'senior',
    foodType: 'wet',
    healthNeeds: ['digestion'],
    shortDescription: 'Pate mịn cho mèo lớn tuổi, dễ ăn và dễ tiêu hóa.',
    description: 'Kết cấu mềm, giảm muối, bổ sung chất xơ hòa tan cho mèo trên 7 năm tuổi.',
    image: IMAGES.osmonSmall,
    tags: ['senior', 'pate'],
    rating: 4.6,
    reviewCount: 47,
    soldCount: 220,
    viewCount: 1120,
  },
  {
    sku: 'PW-DEMO-010',
    name: 'Hạt Senior Light Cá Tuyết',
    brand: 'Me-O',
    categorySlug: 'hat-kho-cho-meo',
    price: 189000,
    salePrice: 169000,
    stock: 55,
    weight: '1.1kg',
    flavor: 'Cá tuyết',
    ageRange: 'senior',
    foodType: 'dry',
    healthNeeds: ['hairball', 'skin'],
    shortDescription: 'Hạt ít béo cho mèo lớn tuổi, hỗ trợ kiểm soát búi lông.',
    description: 'Công thức calo vừa phải, nhiều chất xơ và omega để duy trì lông khỏe.',
    image: IMAGES.kitPurple,
    tags: ['senior', 'hat kho'],
    rating: 4.4,
    reviewCount: 34,
    soldCount: 145,
    viewCount: 930,
  },
  {
    sku: 'PW-DEMO-011',
    name: 'Súp Thưởng Bí Đỏ Tiêu Hóa',
    brand: 'Doca',
    categorySlug: 'snack-treat',
    price: 29000,
    salePrice: null,
    stock: 240,
    weight: '4 tuýp x 15g',
    flavor: 'Gà bí đỏ',
    ageRange: 'all',
    foodType: 'wet',
    healthNeeds: ['digestion'],
    shortDescription: 'Súp thưởng có bí đỏ, dùng kèm bữa chính hoặc khi mèo biếng ăn.',
    description: 'Topping ướt giúp bổ sung nước và chất xơ hòa tan.',
    image: IMAGES.bowlFood,
    tags: ['sup thuong', 'tieu hoa'],
    rating: 4.8,
    reviewCount: 162,
    soldCount: 1100,
    viewCount: 3700,
  },
  {
    sku: 'PW-DEMO-012',
    name: 'Snack Hairball Control',
    brand: 'Me-O',
    categorySlug: 'snack-treat',
    price: 49000,
    salePrice: 39000,
    stock: 160,
    weight: '60g',
    flavor: 'Cá ngừ',
    ageRange: 'adult',
    foodType: 'dry',
    healthNeeds: ['hairball'],
    shortDescription: 'Snack giòn hỗ trợ giảm búi lông cho mèo lông dài.',
    description: 'Bánh thưởng nhiều chất xơ, phù hợp dùng 2-3 lần mỗi tuần.',
    image: IMAGES.kitPurple,
    tags: ['snack', 'hairball'],
    rating: 4.5,
    reviewCount: 71,
    soldCount: 310,
    viewCount: 1560,
  },
  {
    sku: 'PW-DEMO-013',
    name: 'Sữa Bột Mèo Mẹ Và Mèo Con',
    brand: 'Nature Bridge',
    categorySlug: 'sua-nuoc-uong',
    price: 165000,
    salePrice: 149000,
    stock: 48,
    weight: '300g',
    flavor: 'Sữa dê',
    ageRange: 'kitten',
    foodType: 'supplement',
    healthNeeds: ['mother', 'digestion'],
    shortDescription: 'Sữa bột hỗ trợ mèo mẹ sau sinh và mèo con cai sữa.',
    description: 'Công thức tách lactose, thêm canxi và probiotic dịu nhẹ.',
    image: IMAGES.osmonPodium,
    tags: ['sua', 'meo me', 'kitten'],
    isFeatured: true,
    rating: 4.9,
    reviewCount: 66,
    soldCount: 250,
    viewCount: 1880,
  },
  {
    sku: 'PW-DEMO-014',
    name: 'Nước Uống Taurine Da Lông',
    brand: 'Unicharm',
    categorySlug: 'sua-nuoc-uong',
    price: 42000,
    salePrice: null,
    stock: 100,
    weight: '200ml',
    flavor: 'Cá ngừ',
    ageRange: 'all',
    foodType: 'supplement',
    healthNeeds: ['skin', 'hairball'],
    shortDescription: 'Nước uống bổ sung taurine, omega và độ ẩm cho mèo ít uống nước.',
    description: 'Dùng kèm bữa hạt khô để tăng lượng nước nạp vào hằng ngày.',
    image: IMAGES.osmonSmall,
    tags: ['nuoc uong', 'da long'],
    rating: 4.6,
    reviewCount: 45,
    soldCount: 190,
    viewCount: 1040,
  },
  {
    sku: 'PW-DEMO-015',
    name: 'Kit Mèo Mẹ Sau Sinh',
    brand: 'PawWorld',
    categorySlug: 'meal-kit-ca-nhan-hoa',
    price: 520000,
    salePrice: 489000,
    stock: 18,
    weight: '7 ngày',
    flavor: 'Gà, cá hồi & sữa',
    ageRange: 'adult',
    foodType: 'mixed',
    healthNeeds: ['mother', 'digestion', 'skin'],
    shortDescription: 'Gói 7 ngày tăng năng lượng cho mèo mẹ đang cho con bú.',
    description: 'Phối hạt, pate và sữa bổ sung để hỗ trợ phục hồi sau sinh.',
    image: IMAGES.kitPurple,
    tags: ['meo me', 'meal kit'],
    isFeatured: true,
    rating: 4.8,
    reviewCount: 28,
    soldCount: 84,
    viewCount: 880,
  },
  {
    sku: 'PW-DEMO-016',
    name: 'Pate Skin Care Cừu Non',
    brand: 'Doca',
    categorySlug: 'pate-sot-meo',
    price: 38000,
    salePrice: null,
    stock: 132,
    weight: '85g',
    flavor: 'Cừu non',
    ageRange: 'adult',
    foodType: 'wet',
    healthNeeds: ['skin'],
    shortDescription: 'Đồ ăn ướt ít dị ứng cho mèo có vấn đề về da.',
    description: 'Protein cừu non, dầu cá và vitamin E giúp chăm sóc da nhạy cảm.',
    image: IMAGES.kitRed,
    tags: ['pate', 'skin care'],
    rating: 4.4,
    reviewCount: 53,
    soldCount: 190,
    viewCount: 990,
  },
  {
    sku: 'PW-DEMO-017',
    name: 'Hạt Indoor Low Grain',
    brand: 'SmartHeart',
    categorySlug: 'hat-kho-cho-meo',
    price: 259000,
    salePrice: null,
    stock: 74,
    weight: '1.4kg',
    flavor: 'Gà tây',
    ageRange: 'adult',
    foodType: 'dry',
    healthNeeds: ['digestion', 'skin'],
    shortDescription: 'Hạt ít ngũ cốc cho mèo nuôi trong nhà, dễ tiêu hóa.',
    description: 'Công thức cân bằng năng lượng, giảm mùi phân và bổ sung omega.',
    image: IMAGES.bowlFood,
    tags: ['hat kho', 'indoor'],
    rating: 4.5,
    reviewCount: 82,
    soldCount: 330,
    viewCount: 1610,
  },
  {
    sku: 'PW-DEMO-018',
    name: 'Pate Recovery Mèo Ốm',
    brand: 'Royal Pet',
    categorySlug: 'pate-sot-meo',
    price: 55000,
    salePrice: 49000,
    stock: 70,
    weight: '100g',
    flavor: 'Gà hầm',
    ageRange: 'all',
    foodType: 'wet',
    healthNeeds: ['digestion'],
    shortDescription: 'Pate năng lượng cao, mềm mịn cho mèo đang hồi phục.',
    description: 'Dễ ăn, dễ tiêu, phù hợp giai đoạn mèo biếng ăn hoặc sau điều trị.',
    image: IMAGES.osmonPodium,
    tags: ['pate', 'recovery'],
    rating: 4.7,
    reviewCount: 31,
    soldCount: 122,
    viewCount: 720,
  },
  {
    sku: 'PW-DEMO-019',
    name: 'Máy Nước Mini Paw Fountain',
    brand: 'PawWorld',
    categorySlug: 'phu-kien-an-uong',
    price: 390000,
    salePrice: 349000,
    stock: 22,
    weight: '1.8L',
    flavor: '',
    ageRange: 'all',
    foodType: 'accessory',
    healthNeeds: [],
    shortDescription: 'Máy nước nhỏ gọn giúp mèo uống nước thường xuyên hơn.',
    description: 'Dòng nước tuần hoàn yên tĩnh, có lõi lọc than hoạt tính.',
    image: IMAGES.osmonSmall,
    tags: ['phu kien', 'may nuoc'],
    rating: 4.6,
    reviewCount: 24,
    soldCount: 96,
    viewCount: 860,
  },
  {
    sku: 'PW-DEMO-020',
    name: 'Bát Ăn Chống Gù Cổ',
    brand: 'PawWorld',
    categorySlug: 'phu-kien-an-uong',
    price: 99000,
    salePrice: null,
    stock: 80,
    weight: '15 độ',
    flavor: '',
    ageRange: 'all',
    foodType: 'accessory',
    healthNeeds: [],
    shortDescription: 'Bát nghiêng giúp mèo ăn thoải mái và hạn chế rơi vãi.',
    description: 'Chất liệu nhựa an toàn, dễ vệ sinh, phù hợp hạt khô và pate.',
    image: IMAGES.bowlFood,
    tags: ['phu kien', 'bat an'],
    rating: 4.3,
    reviewCount: 39,
    soldCount: 210,
    viewCount: 920,
  },
];

function attachCategory(products, categoryMap) {
  return products.map((product) => {
    const category = categoryMap.get(product.categorySlug);
    if (!category) {
      throw new Error(`Missing category for ${product.name}: ${product.categorySlug}`);
    }

    return {
      ...product,
      category: category._id,
      images: [product.image],
      ingredients:
        product.ingredients ||
        'Thịt và cá chọn lọc, dầu cá, taurine, vitamin, khoáng chất và chất xơ tự nhiên.',
      isActive: product.isActive ?? true,
      reviewCount: product.reviewCount || 0,
      soldCount: product.soldCount || 0,
      viewCount: product.viewCount || 0,
    };
  });
}

async function seedAdmin() {
  const email = (process.env.SEED_ADMIN_EMAIL || 'admin@pawworld.vn').toLowerCase();
  const existingAdmin = await Admin.findOne({ email });

  if (existingAdmin) {
    console.log(`Admin exists: ${email}. Updating name and password.`);
    existingAdmin.name = process.env.SEED_ADMIN_NAME || 'Paw World Admin';
    existingAdmin.password = process.env.SEED_ADMIN_PASSWORD || 'pawworld@123';
    existingAdmin.role = 'admin';
    existingAdmin.isActive = true;
    await existingAdmin.save();
    console.log(`Updated admin: ${email}`);
    return;
  }

  await Admin.create({
    name: process.env.SEED_ADMIN_NAME || 'Paw World Admin',
    email,
    password: process.env.SEED_ADMIN_PASSWORD || 'pawworld@123',
    role: 'admin',
    isActive: true,
  });
  console.log(`Created admin: ${email}`);
}

(async () => {
  try {
    await connectDB();
    await seedAdmin();

    await Promise.all([Product.deleteMany({}), Category.deleteMany({}), Cart.deleteMany({})]);
    console.log('Cleaned old products, categories, and carts.');

    const categories = await Category.create(CATEGORIES);
    const categoryMap = new Map(categories.map((category) => [category.slug, category]));
    const products = attachCategory(PRODUCT_DEMOS, categoryMap);
    await Product.create(products);

    console.log(`Seeded categories: ${categories.length}`);
    console.log(`Seeded products: ${products.length}`);
    console.log('Seed completed.');
    process.exit(0);
  } catch (err) {
    console.error('Seed failed:', err);
    process.exit(1);
  }
})();
